Use millisecond semantic to match automerge-core
automerge/automerge-swift pull request #141
Opened 2024-04-01 12:10 UTC by lightsprint09

This changes timestamp to use milliseconds as documented [here](https://automerge.org/automerge-binary-format-spec/#_value). Date is now used to represent a timestamp, to prevent mistakes when encoding/decoding. Converting Date to FFI representation is now in a single file

2024-04-01 12:42 UTC, ept commented
Hold on a minute, is it actually correct that automerge-core uses milliseconds resolution? I thought it was using seconds.

2024-04-01 12:44 UTC, ept commented
Oh sorry, we're talking about timestamps that appear in the document data. Yes, for those we use milliseconds. I thought we were talking about the change timestamp, which I believe uses integer seconds.

2024-04-01 15:21 UTC, heckj requested changes
Thanks Lucas

Is there any place that we have a unified document with all the various data representations that we could use to verify the assertion that it's in milliseconds with Javascript and/or Rust? I'd really like to get _something_ that's concrete to verify the assertions of representation like this, especially since it was a mistake I made early on and jsut never caught, since I wasn't using this cross-platform - although that's the goal here.

2024-04-01 15:21 UTC, heckj commented on Sources/Automerge/ScalarValue.swift
> +    /// A 64-bit signed integer representing milliseconds since the unix epoch
```suggestion
    /// A 64-bit signed integer that represents the number of milliseconds since the UNIX epoch.
```

2024-04-01 15:30 UTC, heckj commented
Note for release: we'll want to make sure to broadcast loudly that this changed - if anyone already has Date representations in their Automerge docs created, this will cause all of their Date values to be "broken", since we were representing them differently.

2024-04-01 15:34 UTC, alexjg commented
I also missed this so I think having some kind of concrete interop test would be a good idea, though I'm not sure exactly what that would look like.

2024-04-01 15:35 UTC, alexjg commented
In terms of written documentation the [value section](https://automerge.org/automerge-binary-format-spec/#_value) of the binary format docs exists but is quite dense.

2024-04-01 15:43 UTC, heckj commented
@alexjg I was thinking exactly the same thing just a few minutes earlier. Especially for the various language implementations, I think it would be a great idea. Maybe even just a document that has one of each of the .scalarValue data blobs within it, with specific values, and an external representation. In practice, and looking through the .scalarValue data types, I think the only one that's subject to "local interpretation" is the timestamp value, but as we advance into more "attributed strings" territory, I think the concept of a common reference document will hold us in good stead, and we can make sure that some level of "marks" or attributes/blocks are equally matched in cross-platform representations.

2024-04-01 20:47 UTC, heckj commented
@lightsprint09 I think your rebasing went a bit awry here, GH is complaining about it being "unmergable"

2024-04-02 16:57 UTC, lightsprint09 commented
Looks good to me?

2024-04-02 18:47 UTC, heckj commented
<img width="754" alt="Screenshot 2024-04-02 at 11 47 44 AM" src="https://github.com/automerge/automerge-swift/assets/43388/23a2797e-0c29-4aca-a324-d2b1ab324d17">

2024-04-02 18:53 UTC, lightsprint09 commented
<img width="989" alt="Bildschirmfoto 2024-04-02 um 20 53 13" src="https://github.com/automerge/automerge-swift/assets/3703083/ec953129-aee4-4f1c-8c0b-e6730032cc93">

hmm ;)

2024-04-02 18:55 UTC, heckj approved these changes

2024-04-02 18:56 UTC, heckj commented
Odd - if you can merge it, go ahead - it's been complaining since you merge back the main branch, but if it's clear for you, awesome.

2024-04-02 19:37 UTC, merged